name: Create Artifacts
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Flutter Environment
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate Android
        run: flutter build apk --split-per-abi
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: 'APK generated'
          path: 'build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk'
          if-no-files-found: error